### ISSUE TITLE
streaming code is missing.

### ISSUE THREAD

**Issue by carlosjs23** [juliocesar-io/voyager-bot#1]
Hi @juliocesar-io, I need some idea about how video streaming is done in this project to make a similar implementation in my project, but the code is not available.

best regards

**Comment by juliocesar-io** [comment]
Hey, @carlosjs23 you mean streaming video from a Raspberry Pi? If so, I made a separated implementation in another repo here (because of too many concerns in just one repo) [https://github.com/juliocesar-io/web-cam-streaming](https://github.com/juliocesar-io/web-cam-streaming) using EasyRTC, Socket.io and Express. You can it use with raspberry, take a look [here](https://github.com/priologic/easyrtc/issues/205).

If you want something more low-level, you can use [Janus WebRTC](https://github.com/meetecho/janus-gateway) along with Nginx It works well with Raspberry Pi.

Finally, I let you know I'm working with a Photon board from [Particle.io](https://www.particle.io/) (similar to Arduino) to also make a video streaming just with C++ code. I will share the code as soon as I have something done.

**Comment by juliocesar-io** [comment]
In the meantime, I will clean this repo and organize all there with Docker. Will be nice to have your support to make a nice framework for real-time web interaction with Hardware. 🆒

**Comment by carlosjs23** [comment]
Oh okay, I'll check it out.

Of course I can help, I'll get in touch with you to talk about it.
